#pragma once
#include "../glm/glm.hpp"
#include "../glm/gtc/matrix_transform.hpp"
#include <stdio.h>
#include "glad/glad.h"
#include <iostream>
#include <vector>
#include "stb_image.h"
#include "../glm/gtc/type_ptr.hpp"